;Multiplication of two sixteen bit numbers

	AREA MULTIPLY, CODE, READONLY
	ENTRY
	
	LDRH R1, NUM1  ;LOAD THE FIRST NUMBER
	LDRH R2, NUM2	;LOAD THE SECOND NUMBER
	
	MUL R3, R1, R2	;MULTIPLICATION
	
	LDR R0, PRODUCT
	STR R3, [R0]
	
	
B1 	B	B1

NUM1	DCW 10
NUM2	DCW 10
PRODUCT DCD 0x40000000
		END