; Program to add first ten integers

		AREA ADDTEN, CODE, READONLY
		ENTRY
		
		MOV R0, #10 	;COUNTER
		MOV R1,#0 	;SUM
		MOV R2, #1 ;FIRST NUMBER
		
LOOP	ADD R1,R1,R2	;ADDITION, ADD R1,R2 AND STORE IT IN R1 
		ADD R2, #1		;INCREMENT R2
		SUBS R0, #1		;dECREMENT COUNTER  
		BNE LOOP
		
		LDR R3,RESULT
		STR R1,[R3]
STOP 	B 	STOP
		
RESULT 	DCD 0X40000000
		END